# This deploy configuration contains all routes, schemas and connections of the
# app. The configuration can be deployed through the following command:
# > php bin/fusio deploy

config: !include resources/config.yaml
connections: !include resources/connections.yaml
event: !include resources/event.yaml
routes: !include resources/routes.yaml
