language: php
php:
  - 7.3
  - 7.4
  - 8.0
sudo: false
services:
  - mysql
before_install:
  - mysql -e 'create database fusio;'
install:
  - composer install
  - php bin/fusio install --no-interaction
before_script:
  - php bin/fusio migration:migrate --connection=System --no-interaction
  - php bin/fusio adduser --role=1 --username="test" --email="test@fusio-project.org" --password="test1234"
  - php bin/fusio login --username="test" --password="test1234"
  - php bin/fusio deploy
script:
  - vendor/bin/phpunit
