"/page": !include resources/routes/page/collection.yaml
"/page/:page_id": !include resources/routes/page/entity.yaml
"/post": !include resources/routes/post/collection.yaml
"/post/:post_id": !include resources/routes/post/entity.yaml
